### ISSUE TITLE
User Location Live Family Tracking

### ISSUE THREAD

**Issue by jeffwong97** [gcivil-nyu-org/fall24-monday-team4#9]
## User Story
As a family tracker, I want to be able to view and track my User Contact's live location while they are on a trip if they choose to share it.
>
## Acceptance Criteria

- [ ] **Scenario: User can enable live location sharing for their trips**
  - Given the user is about to go on a trip or is currently on a trip
  - When the user enables live location sharing
  -  If the user has not designated a Family Tracker they can designate one
  -  The Family Tracker receives a link via text and/or email to view the User's status in the app
  - Then the user's live location should be visible to family members who have been granted access
>
- [ ] **Scenario: User can disable live location sharing at any time**
  - Given the user has enabled live location sharing for their trip
  - When the user disables live location sharing in the app settings
  - Then the user's live location should no longer be visible to family members who have been granted access
>
- [ ] **Scenario: Family members can view and track the User Contact's live location**
  - Given a family member has been granted access to view the User Contact's live location
  - When the User Contact is on a trip with live location sharing enabled
  - Then the family member should be able to see the User Contact's current location and track their movements in real-time
>
- [ ] **Scenario: Live location updates are sent frequently enough for accurate tracking**
  - Given the User Contact has enabled live location sharing
  - When the User Contact is on a trip with live location sharing enabled
  - Then the family members should receive frequent updates to the User Contact's location, allowing them to accurately track their movements
>
## Definition of Done
- [ ]  Ability for user to set a designated Family Tracker in app
- [ ]  Ability for user to share live location to designated Family Tracker while on a trip
- [ ]  Text and email alert to Family Tracker once user has shared live location
- [ ]  Ability for Family Tracker to view user's live location in app via link in text/email
